# Generated by Django 4.0.1 on 2022-01-24 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('description', models.CharField(default='Some fee', max_length=200, verbose_name='fee_description')),
                ('fee_value', models.DecimalField(decimal_places=5, default=0.015, max_digits=10, verbose_name='fee_value')),
            ],
            options={
                'verbose_name': 'Fee Percentage',
                'verbose_name_plural': 'Fees Percentages',
                'db_table': 'fees',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('first_name', models.CharField(max_length=255, verbose_name='inversor_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='inversor_last_name')),
                ('company_name', models.CharField(blank=True, default='No company', max_length=255, null=True, verbose_name='company_name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='investment_amount')),
                ('date_of_investment', models.DateField(default=datetime.datetime.today, verbose_name='date_of_investment')),
                ('pay_upfront', models.BooleanField(default=False, verbose_name='pay_upfront')),
                ('fee_percentage', models.ForeignKey(default=0.015, on_delete=django.db.models.deletion.CASCADE, to='investor.feepercentage')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
            },
        ),
    ]
