# Generated by Django 4.0.1 on 2022-01-24 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('description', models.CharField(default='Fee for first year', max_length=200, verbose_name='description')),
                ('fee_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=10, verbose_name='fee_amount')),
                ('invoice_expire_date', models.DateField(blank=True, null=True, verbose_name='invoice_expire_date')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investment')),
            ],
            options={
                'verbose_name': 'Yearly Fee',
                'verbose_name_plural': 'Yearly Fees',
                'db_table': 'yearly_fees',
            },
        ),
        migrations.CreateModel(
            name='Upfront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('upfront_fee_amount', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='upfront_fee_amount')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investment')),
            ],
            options={
                'verbose_name': 'Upfront fee',
                'verbose_name_plural': 'Upfront fees',
                'db_table': 'upfront_fees',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('membership_amount', models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='membership_amount')),
                ('year_of_membership', models.IntegerField(default=1, verbose_name='year_of_membership')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'memberships',
            },
        ),
    ]
