# Generated by Django 4.0.1 on 2022-01-24 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
        ('investments_fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('cash_call_expire', models.DateField(default=datetime.date(2022, 2, 9), verbose_name='cash_call_expire')),
                ('state', models.CharField(choices=[('G', 'generated'), ('V', 'validated'), ('S', 'sent by email'), ('P', 'paid'), ('O', 'overdue')], default='G', max_length=1, verbose_name='state')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
                ('membership', models.ManyToManyField(blank=True, to='investments_fees.Membership')),
                ('upfront_fees', models.ManyToManyField(blank=True, to='investments_fees.Upfront')),
                ('yearly_before', models.ManyToManyField(blank=True, to='investments_fees.YearlyFees')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
            },
        ),
    ]
